version: '3.2'

services:
  apache:
    build:
      dockerfile: php7-apache2-dockerfile
      context: .
    # image: 'php:7.2-apache'
    # container_name: php
    image: php7-apache2-dockerfile
    container_name: php7-apache2
    restart: always
    ports:
      - '80:80'
    volumes:
      - '.:/var/www/html'
      # - './php.ini:/usr/local/etc/php/php.ini'
    # depends_on:
    #   - mysqldb
    # links:
    #   - mysqldb

  # mysqldb:
  #   container_name: mysqlASW
  #   image: mysql:5.7
  #   restart: always
  #   ports:
  #     - '3307:3306'
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=biblioteca
